---
title: "Session2"
---
       
```{r}
library(tidyverse)
library(nycflights13)
glimpse(flights)
```

```{r}
#correct format
flights |>
  filter(month == 1 | month == 2) |>
  group_by(month) |>
  count()
```


```{r}
#wrong format
flights |>
  filter(month == 1 | 2)|>
  group_by(month) |>
  count()
```

```{r}
#format for one month filtering
flights |>
  filter(month == 1)|>
  group_by(month) |>
  count()
```

```{r}
flights |>
  filter(month == 1 | month == 2) |>
  select(month, origin, dest, dep_time, arr_time, arr_delay) |>
  arrange(dep_time) |>
  distinct(origin,dest, .keep_all = TRUE)


```

```{r}
flights |>
  count(origin, dest, sort = TRUE)
```

```{r}
flights_updated <- 
flights %>%
  mutate(
    diff = dep_delay - arr_delay,
    speed = distance / air_time * 3600,
    .before = 1
  )
flights_updated
```

```{r}
flights_updated <- 
flights %>%
  mutate(
    diff = dep_delay - arr_delay,
    speed = distance / air_time * 3600,
    .after = dep_time
  )
flights_updated
```

```{r}
flights_updated |>
  select(!year : sched_dep_time)
```

```{r}
flights |>
  rename(delay = dep_delay)
```

```{r}
table1 |>
  mutate(rate_of_spread = cases / population * 5000) |>
  group_by(year) |>
  summarize(total_spread = mean(rate_of_spread))
```

```{r}
ggplot(table1, aes(x = year, y = cases))+
  geom_line(aes(group = country))+
  geom_point(aes(color = country, shape = country))+
  scale_x_continuous(breaks = c(1999,2000))
```

```{r}
mpg |>
  select(class) |>
  group_by(class) |>
  count()

#mpg$class
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy))+
  geom_point(color = "blue")
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy))+
  geom_point()+
  geom_point(
    data = mpg |> filter(class == "2seater"),
    color = "red"
  )+
  geom_point(
    data = mpg |> filter(class == "2seater"),
    shape = "circle open", size = 3, color = "red"
  )
  
```

```{r}
ggplot(mpg, aes(x = displ, y = hwy, color = class))+
  geom_point()+
  facet_grid(drv ~ cyl, scales = "free")
```

```{r}
plt <-
ggplot(data = mpg) +
  geom_bar(
    mapping = aes(x = manufacturer, fill = manufacturer),
    show.legend = FALSE,
    width = 1
  )
```

```{r}
plt + coord_flip()
plt + coord_radial() + theme_classic()
```

