name: Render Rmd, Build Jekyll Site & Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up R (for rendering Rmd files)
      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      # Install R packages required for rendering
      - name: Install R packages
        run: |
          Rscript -e "install.packages('rmarkdown', repos = 'https://cran.r-project.org')"

      # Render each R Markdown file in /rmds to HTML files in /htmls
      - name: Render R Markdown Files to HTML
        run: |
          mkdir -p htmls
          for file in rmds/*.Rmd; do
            echo "Rendering $file..."
            Rscript -e "rmarkdown::render('$file', output_dir = 'htmls')"
          done

      # Set up Ruby and install Jekyll dependencies
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - name: Install Bundler and Jekyll
        run: |
          gem install bundler
          bundle install

      # Build the Jekyll site (this processes your Liquid templates)
      - name: Build Jekyll Site
        run: bundle exec jekyll build

      # Deploy the built site (from _site) to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
